### PR TITLE
MouseWheel click for moving sample in preview window

### PR DESCRIPTION
**Pull request by vollrathf**

### CODE REVIEW

**Comment by raacampbell** [comment]
Thanks for this. There are a few things here we need to resolve before merging this:

1. What is the failure with the ensemble controller? I'm trying to understand why it fails. BUILD_GENERIC_STAGE works for everything else but this. Can you check?
2. The behavior of `size` is changed recently in MATLAB. If you upgrade to R2019b you will not have to change that line.
3. For the motion commands you want `hBT.moveXYto(stagePos)`  Then do `hBT.xAxis.axisPosition` and `hBT.yAxis.axisPoisition` to update the positions. Maybe the latter two should take placed within `moveXYto` but there are reasons why I haven't done that so far. 
4. You shouldn't need the new property for the figure window. It is already there as `hFig`. This is inherited from `child_view`, which is why you didn't see it.

**Comment by vollrathf** [comment]
Hi Rob,
I fixed points 2-4.

I don't really know what the problem is. The error appears in builMotionComponent.m in the line 
        component = eval([controllerName,'(stageComponents)']);


Matlab says: 

Error using linearcontroller/attachLinearStage (line 300)

linearstage object not provided

Error in ensemble (line 93)
              obj.attachLinearStage(stageObject);
BakingTray return is:

FAILED TO BUILD AXIS: zAxis

linearstage object not provided

	linearcontroller.attachLinearStage - C:\Users\superuser\Documents\MATLAB\BakingTrayGIT\BakingTray\code\components\motion\linearcontroller.m (line: 300)

	ensemble.ensemble - C:\Users\superuser\Documents\MATLAB\BakingTrayGIT\BakingTray\code\components\motion\ensemble.m (line: 93)

	buildMotionComponent - C:\Users\superuser\Documents\MATLAB\BakingTrayGIT\BakingTray\code\components\motion\buildMotionComponent.m (line: 121)

	attachMotionAxes - C:\Users\superuser\Documents\MATLAB\BakingTrayGIT\BakingTray\code\@BT\attachMotionAxes.m (line: 73)

	BT.BT - C:\Users\superuser\Documents\MATLAB\BakingTrayGIT\BakingTray\code\@BT\BT.m (line: 246)

	BakingTray - C:\Users\superuser\Documents\MATLAB\BakingTrayGIT\BakingTray\code\BakingTray.m (line: 56)


linearstage object not provided

BT.attachMotionAxes failed to build one or more axes. Not starting BT.



The implementation we made is creating a generic_AeroTechZJack, using BUILD_GENERIC_STAGE is creating an ensemble object. The properties of these two are different. I guess that’s causing the error. For me, it is not really clear what the optimal way could be. Maybe you can have another look here. I was inheriting the ensemble class from linearcontroller. Could it be that it needs to be inherited from linearstage? But the soloist class is not either. Let me know what you think.

**Comment by raacampbell** [comment]
What is in your `components` settings file for this Z axis? You can just copy/paste that here.

**Comment by vollrathf** [comment]
nC=3;
    motionAxis(nC).type='ensemble';
    motionAxis(nC).settings.connectAt.interface='usb';
    motionAxis(nC).settings.connectAt.ID='618526-1-1';
%     motionAxis(nC).settings.connectAt.controllerModel='soloist';

    motionAxis(nC).stage.type='ensemble';
    motionAxis(nC).stage.settings.invertDistance=1;
    motionAxis(nC).stage.settings.positionOffset=0;
    motionAxis(nC).stage.settings.axisName='zAxis';
    motionAxis(nC).stage.settings.minPos=0;
    motionAxis(nC).stage.settings.maxPos=22;

**Comment by raacampbell** [comment]
Ok, good, that's what I thought. Your stage type is listed as ensemble,
which is a controller. It should be a stage class. So the generic Aerotech
stage class in your case. If you do that I believe the
buildMotionComponent.m I have in my branch will work for you, and you won't
need the separate case statement.


Rob

**Comment by vollrathf** [comment]
But wouldn't we need then a GenericAerotechStage in the case of ensemble?
What branch do you mean? Do you have a example?

**Comment by raacampbell** [comment]
Just to be clear: What is the model of your stage and what is the model of
your controller?

The branch I'm talking about is mine. What is in my buildMotionComponent.

**Comment by vollrathf** [comment]
We are using a PRO225SV controlled by a EnsembleCP10.
I changed our componentSettings.m to
    nC=3;
    motionAxis(nC).type='generic_AeroTechZJack';
    % motionAxis(nC).type='ensemble';
    motionAxis(nC).settings.connectAt.interface='usb';
    motionAxis(nC).settings.connectAt.ID='618526-1-1';
    motionAxis(nC).settings.connectAt.controllerModel='ensemble';
    motionAxis(nC).stage.settings.invertDistance=1;
    motionAxis(nC).stage.settings.positionOffset=0;
    motionAxis(nC).stage.settings.axisName='zAxis';
    motionAxis(nC).stage.settings.minPos=0;
    motionAxis(nC).stage.settings.maxPos=22;

I think there is something wrong still. Could you please quickly check?

**Comment by raacampbell** [comment]
I think it's because you have:
```
motionAxis(nC).type='generic_AeroTechZJack';
```
not
```
motionAxis(nC).stage.type='generic_AeroTechZJack';
```


Then uncomment:
```
% motionAxis(nC).type='ensemble';
```

The logic is that the motion axis is being controlled by an `ensemble` controller that has connected to it a stage that is of type `generic_AeroTechZJack`. It's max and min positions, etc, are defined in the structure. 

My settings for a soloist are:

```
    motionAxis(nC).type='soloist'; 
    motionAxis(nC).settings.connectAt.interface='ethernet';
    motionAxis(nC).settings.connectAt.ID='618277-1-1'; %The controller ID as listed in Soloist software
    motionAxis(nC).settings.connectAt.controllerModel='Soloist MP'; %Likely not critical

    motionAxis(nC).stage.type='generic_AeroTechZJack'; % One of: 'genericPIstage',  'DRV014', or 'dummy_linearstage'
  
    motionAxis(nC).stage.settings.invertAxis=false;
    motionAxis(nC).stage.settings.axisName='zAxis'; 
    motionAxis(nC).stage.settings.minPos=0;
    motionAxis(nC).stage.settings.maxPos=35;

```



You will also need to have in place the `buildMotionComponent.m` from my `dev` branch.

**Comment by vollrathf** [comment]
Thanks, it it working now!

**Comment by raacampbell** [comment]
Nice, thanks so much. I will merge and try this.

**Comment by raacampbell** [comment]
I merged some other changes on my end. Can you check it all still behaves as expected if you use my `dev` branch. i.e. that the stage and controller build and that you can middle-click to move. 

The branch also adds a sample > new menu option. The idea is that you use this before starting a new sample. 

I will test and merge all this into `master` soon.

**Comment by raacampbell** [comment]
It's merged into `master` I added a check so it can't move the stage during slicing. I also made the XY motion blocking, so the stage positions are not read until the motion is complete. 

Thanks, it's really a useful addition and very nice to use.

**Pull request merged**
